title: Thomas Massena
description: Personal website
baseurl: ""
url: "https://massena-t.github.io"

markdown: kramdown

collections:
  various:
    output: true
    permalink: /various/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
